### ISSUE TITLE
Section 2.1.1 - use of word content (Wilco Fiers)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#1]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0001
## Original Comment

Content types : This confused me a bit, because of the word 'content'. In WCAG the word 'content' means something different then it does in HTTP. I think for WCAG what is called 'content' here is actualy 'technologies'. Maybe something like "Processed technologies" is clearer, as the main question here seems to be, does the tool look at just the HTML, or does it take CSS, Javascript, etc. into account?

**Comment by nitedog** [comment]
## Resolution

Accept - See also Issue #10 and Issue #51

**Comment by ysmartin** [comment]
While I agree that "content" is a misleading term (CSS and JS do not qualify as content, at least with its usual meaning), I would talk about "formats" rather than "technologies", as the former is more specific.
