### ISSUE TITLE
Section 2.1.1 - css and javascript (Karl Groves)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#10]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Jul/0005
## Original Comment

This section discusses, ostensibly, the content types which evaluation tools can/ should test.  If this is in fact the case, then the following comments apply:
CSS & JavaScript

Current state-of-the art for automated accessibility testing cannot, will-not, and ought-not test CSS or JavaScript outside of the context of the way they affect a web document being tested. The testing of both of these content types is only relevant in such context due to their relationship with the browser DOM.  The testing of CSS or JavaScript files by themselves would be exceedingly complex and have little actual value for accessibility evaluation.  For instance, actually testing color-contrast of an object on a web page would require testing more than the style sheet declarations and instead would necessitate testing the computed style for the object.  Consider the following structure:

```
<body>

<main>

<div id="some-stuff">

<!--content-->

</div>

</main>

</body>
```

And consider the following styles for that HTML:

```
body{

    background-color: #fff;

} 

main{

   background-color: #333;

}

#some-stuff{

    color: #fff;

}
```

Given the above, calculation of the color contrast for #some-stuff would require measuring the text color of #some-stuff against the background-color of the main element.  The necessary information to check the color contrast of #some-stuff is not available outside of the browser context. The same goes for the testing of JavaScript.  The ERT WG should clarify this for the end user.

**Comment by nitedog** [comment]
## Resolution

Accept - See also Issue #51 and Issue #1

**Comment by ysmartin** [comment]
I agree on the main arguments. However, I would not completely rule out CSS and JS evaluation on their own (e.g. some evaluation tools warn whenever a font color is specified but a corresponding background color is not specified by either the same rule or one up in the cascade; JS assignment of device-dependent handlers can also be detected, etc.)
