### ISSUE TITLE
Section 2 - definition of accessibility evaluation tool (Jan Richards)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#17]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0000
## Original Comment

It would help if the "Features of an accessibility evaluation tool" terminology matched the wording of features in the list of evaluation tools (http://www.w3.org/WAI/ER/tools/advanced). Since that older document is to refreshed, perhaps its wording can be refreshed if that makes more sense.

**Comment by nitedog** [comment]
## Resolution

No change - The WAI list of web accessibility evaluation tools will be updated in accordance with this document.
