### ISSUE TITLE
Section 2.4.3 - term web commissioners (Jan Richards)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#28]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0000
## Original Comment

"web commissioners" - I just haven't hear the term before

**Comment by nitedog** [comment]
## Proposed Resolution

Accept - Either "web accessibility evaluation commissioners" or, better, "people commissioning web accessibility evaluations".
