### ISSUE TITLE
Section 2.4.1 - extend description for the integration into bug tracking systems (Wilco Fiers)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#3]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0001
## Original Comment

Workflow integration mentions bug tracking. I would like this to be a little more extensive. For instance, are there protocols that bug/issue trackers use that are recommended? How should you ensure that the same issue get's logged multiple times, either because it comes from a second evaluation or because it's an issue that is in a templated and so it repeats on many pages?

**Comment by nitedog** [comment]
## Resolution

No change - bug management, including handling duplicates, is outside the scope of this document. The main point is to raise awareness that evaluation tools could interact with bug-tracking systems.
