### ISSUE TITLE
Section 1.1 -  inclusion of "web authoring tool" as an "evaluation tool (Sarah E. Bourne)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#33]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0003
## Original Comment

I am puzzled by the inclusion of "web authoring tool" as an "evaluation tool".  Perhaps you mean that some web authoring tools include features for evaluation?  I would like to see clarification on why this is included here.

**Comment by nitedog** [comment]
## Resolution

Accept - Could edit the paragraph beneath. For example, to change "In some cases it can be part of a web authoring tool, or considered to be a web authoring tool depending on the functionality that it provides" to something like "In some cases it can be part of a web authoring tool. In other cases an evaluation tool could be considered to be a web authoring tool, for example if it provides repair functionality that modifies the content."

**Comment by darthcav** [comment]
Also modified the order of the list.
