### ISSUE TITLE
Section 2.3.5 - Result aggregation (Hanno Lans)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#38]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0004
## Original Comment

Result aggregation is also possible in time, to track progress. In Just Accessible we do quarterly audits and compare the results. If errors have unique identifiers/pointers a tool could even provide a list of new, open and resolved errors. This make it possible to have progress scores.

**Comment by nitedog** [comment]
## Resolution

Accept - Reworded section 2.3.5.
