### ISSUE TITLE
Section 3.3 - New tool (Hanno Lans)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#39]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0004
## Original Comment

3.3 Example Tool D: Accessibility tool for richt text editors

Tool D is an accessibility evaluation tool for rich text editors. The tool supports content authors when writing content for web pages.
- The tool lives in the rich text editor with a button
- The tool takes into account the output of the processed html of the richt text editor (page language etc)
- The tool might give suggestions as you type hand additional hints.

**Comment by darthcav** [comment]
## Resolution

Unchanged. The working group finds the proposed tool very interesting. However, time constraints may not allow to include it in this version.

**Comment by nitedog** [comment]
I don't understand what the final sentence means. Actually I like this suggestion very much.
