### ISSUE TITLE
Section 2.1.2 - Encodings (Richard Ishida)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#41]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0005
## Original Comment

"Furthermore, web content can be transmitted using different character encodings and sets (like ISO-8859-1, UTF-8, UTF-16, etc.), which demands from the evaluation tools the capacity to handle them."

HTML5 treats iso 8859-1 as Windows-1252, so maybe better to replace with the latter. However, with HTML5 there is a strong push to abandon legacy encodings and just use UTF-8: it would be good to acknowledge this and, rather than assuming that content can be in many encodings, say that it is possible to sometimes encounter some pages in legacy encodings.

None of those pages are likely to be in UTF-16, and you should remove this from your list of examples.

These comments apply elsewhere in the doc where character encodings are referred to.

**Comment by nitedog** [comment]
## Resolution

Accept
