### ISSUE TITLE
Section 2.3.7 - meeting SCs (Jan Richards)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#49]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0000
## Original Comment

"If the evaluation tool is part of an authoring tool as described in the Authoring Tool Accessibility Guidelines 2.0 [ATAG], then the tool will meet its success criterion B.3.2.1." - Careful how you refer to meeting SC's...the repair functionality must cover the full range of issues the checker could uncover...not just some of them.

**Comment by nitedog** [comment]
## Proposed Resolution

Accept - need to reword. For example by saying something like "SC B.3.2.1 requires checking functionality. Evaluation tools that provide repair options can help meet this requirement" or such.
