### ISSUE TITLE
Section 2.2.2 - Difference between manual and semi-automatic evaluation (Michael Cooper)

### ISSUE THREAD

**Issue by darthcav** [w3c/w3c-waet#54]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0008
## Original Comment

Some examples are needed to help explain the difference between manual and semi-automatic evaluation and why there might be value in each.

**Comment by nitedog** [comment]
## Proposed Resolution

Partial - section will be rewritten to be more descriptive of the different testing modes

**Comment by ysmartin** [comment]
We are using definitions taken from EARL. The update of the definition was recorded as an action for EARL in a previous conference.

**Comment by nitedog** [comment]
## Resolved

Editing suggestions in [Minutes of 3rd September 2014 ERT WG call](http://www.w3.org/2014/09/03-er-minutes.html#item02)
