### ISSUE TITLE
Section 2.1.9 - Endless loops (Hanno Lans)

### ISSUE THREAD

**Issue by nitedog** [w3c/w3c-waet#61]
## Reference

http://lists.w3.org/Archives/Public/public-wai-ert-tools/2014Aug/0004
## Original Comment

An important additional  feature for a web crawler is handling endless loops. With the Just Accessible toolwe decided to crawl every page, but some type of pages exist infinitely. Besides performance it creates problems when calculating the amount of failures. For example calendars with an infinite amount of pages of every future day. A crawlers could have logics for this.

**Comment by nitedog** [comment]
## Resolution

No change - the specifics of how to carry out proposer crawling and manage performance is outside the scope of this document

**Comment by darthcav** [comment]
Without implementation details it will be added to the point on duplicate downloads.
