### ISSUE TITLE
Section 2.4.2 - word redundancy (Samuel Martín)

### ISSUE THREAD

**Issue by ysmartin** [w3c/w3c-waet#64]
http://lists.w3.org/Archives/Public/public-wai-ert/2014Aug/0002.html

> I just caught an editorial issue at the end of 2.4.2: (Localization and Internationalization): "like for instance, such as those related to readability". Either "like for instance" or "such as" are redundant.

**Comment by darthcav** [comment]
## Resolution

Accept.
