### ISSUE TITLE
Section 2.1.1. Wording across definition headers ("resources" vs "formats")

### ISSUE THREAD

**Issue by ysmartin** [w3c/w3c-waet#65]
The list of the different resource formats lists them sometimes as "resources" and others as "formats" [emphasis added]

> The most common **resource formats** include:
> - **Markup resources**: These are normally HTML [ HTML4 , HTML5 ] or XML **documents**. Processing **these resources** typically...
> - **Style resources**
> - **Script resources**
> - **Media resources**
> - **Document formats**
> - **Resources** with other formats

I would suggest making headers more homogeneous (are we listing X format, Y format, or X resources, Y resources?). I am sure readers can understand current wording, but it sounds a bit awkward.

In addition, in the last point, again for coherence, I would say:
Adobe Flash _movies_, Java applets , Microsoft Silverlight _applications_

**Comment by darthcav** [comment]
## Resolution

Accept.
