### ISSUE TITLE
Section 2.3.1 HTML and word processor documents as reporting formats

### ISSUE THREAD

**Issue by ysmartin** [w3c/w3c-waet#66]
From #7 and #13 it was resolved to add a list of alternative reporting formats, to supplement the mentions to EARL. This list now includes "HTML or word processor documents". 

I do not think they fit within the rest of the list (EARL, CSV, JSON) in that the three of them are machine-readable formats which can be used for the purpose of automating interchange and processing of evaluation results, while the former are targeted at human consumption.

**Comment by darthcav** [comment]
Although I understand your point, we have met many times customers that demand from us at the end of the day a word, or an HTML or a PDF document. I would prefer to keep this in the document.

**Comment by darthcav** [comment]
## Resolution

Accept. Reorganise sections under 2.3 to reflect the different types of formats.
